namespace MonoLibUsb;

public enum MonoUsbCapability
{
	LIBUSB_CAP_HAS_CAPABILITY = 0,
	LIBUSB_CAP_HAS_HOTPLUG = 1,
	LIBUSB_CAP_HAS_HID_ACCESS = 256,
	LIBUSB_CAP_SUPPORTS_DETACH_KERNEL_DRIVER = 257
}
